# Agricultural Production Analysis (India)
---
This project analyzes **crop area, production, and yield data across Indian states and seasons**.  
The goal is to clean, transform, and prepare the dataset for further analysis such as:

- State-level agricultural performance
- Crop productivity comparisons
- Seasonal production patterns
- National agricultural trends

The notebook focuses on **data cleaning, restructuring, and data quality validation** to prepare a reliable dataset for later exploratory data analysis and insights.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/Crop-Profile_-State-wise-Area,-Production-&-Yield-of-All-Crops,-(2020-21-to-2024-25).csv")
df.head()

,Crop,State,Season,Area-2020-21,Area-2021-22,Area-2022-23,Area-2023-24,Area-2024-25,Production-2020-21,Production-2021-22,Production-2022-23,Production-2023-24,Production-2024-25,Yield-2020-21,Yield-2021-22,Yield-2022-23,Yield-2023-24,Yield-2024-25
0,Rice,Andaman And Nicobar Islands,Kharif,6256.0,6256.43,4989.65,4557.1,4365.2,13344.05,13344.97,10511.53,9569.91,8992.31,2133.0,2133.0,2107.0,2100.0,2060.0
1,Rice,Andaman And Nicobar Islands,Rabi,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Rice,Andaman And Nicobar Islands,Total,6256.0,6256.43,4989.65,4557.1,4365.2,13344.05,13344.97,10511.53,9569.91,8992.31,2133.0,2133.0,2107.0,2100.0,2060.0
3,Rice,Andhra Pradesh,Kharif,1496000.0,1508000.00,1452000.00,1347297.0,1404000.0,4211240.00,4326452.00,4986168.00,4695330.05,5030532.00,2815.0,2869.0,3434.0,3485.0,3583.0
4,Rice,Andhra Pradesh,Rabi,827500.0,781000.00,677000.00,573340.0,673000.0,3671617.50,3437181.00,2955782.00,2646250.77,3128602.02,4437.0,4401.0,4366.0,4616.0,4649.0

In [3]:
df.shape

(3390, 18)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3390 entries, 0 to 3389
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Crop                3390 non-null   object
 1   State               3390 non-null   object
 2   Season              3390 non-null   object
 3   Area-2020-21        2083 non-null   float64
 4   Area-2021-22        2743 non-null   float64
 5   Area-2022-23        2154 non-null   float64
 6   Area-2023-24        2161 non-null   float64
 7   Area-2024-25        2169 non-null   float64
 8   Production-2020-21  2083 non-null   float64
 9   Production-2021-22  3157 non-null   float64
 10  Production-2022-23  2154 non-null   float64
 11  Production-2023-24  2161 non-null   float64
 12  Production-2024-25  2169 non-null   float64
 13  Yield-2020-21       2083 non-null   float64
 14  Yield-2021-22       2743 non-null   float64
 15  Yield-2022-23       2154 non-null   float64
 16  Yield-2023-24       2161 non-null   float64
 17  Yield-2024-25       2169 non-null   float64
dtypes: float64(15), object(3)
memory usage: 476.8+ KB

In [5]:
df.describe()

,Area-2020-21,Area-2021-22,Area-2022-23,Area-2023-24,Area-2024-25,Production-2020-21,Production-2021-22,Production-2022-23,Production-2023-24,Production-2024-25,Yield-2020-21,Yield-2021-22,Yield-2022-23,Yield-2023-24,Yield-2024-25
count,2.083000e+03,2.743000e+03,2.154000e+03,2.161000e+03,2.169000e+03,2.083000e+03,3.157000e+03,2.154000e+03,2.161000e+03,2.169000e+03,2083.000000,2743.000000,2154.000000,2161.000000,2169.00000
mean,9.683450e+05,7.368519e+05,9.611737e+05,9.587979e+05,9.850301e+05,2.943481e+06,2.005404e+06,3.142043e+06,3.069647e+06,3.221582e+06,3193.409025,2308.778709,3326.707521,3277.111060,3357.41171
std,5.132928e+06,4.475559e+06,5.094594e+06,5.101573e+06,5.300605e+06,1.917070e+07,1.638072e+07,2.153370e+07,2.065365e+07,2.135664e+07,11868.893041,9465.216871,11693.081530,11323.136188,11384.45738
min,0.000000e+00,0.000000e+00,2.000000e-01,8.000000e-01,1.000000e-01,0.000000e+00,0.000000e+00,2.000000e-01,6.500000e-01,9.000000e-02,0.000000,0.000000,87.000000,87.000000,79.00000
25%,1.434000e+03,0.000000e+00,2.352000e+03,2.140000e+03,2.105000e+03,1.548080e+03,0.000000e+00,2.593507e+03,2.396520e+03,2.436190e+03,656.000000,0.000000,795.000000,798.000000,823.00000
50%,2.198000e+04,4.357000e+03,2.548000e+04,2.622000e+04,2.568474e+04,2.801030e+04,1.434000e+03,3.360538e+04,3.391408e+04,3.496955e+04,1088.000000,858.000000,1193.000000,1200.000000,1266.00000
75%,2.913220e+05,1.437010e+05,2.890000e+05,2.784100e+05,2.881950e+05,5.561639e+05,1.107060e+05,5.899894e+05,5.863119e+05,5.865730e+05,2056.000000,1736.500000,2190.750000,2218.000000,2285.00000
max,1.297950e+08,1.301689e+08,1.322043e+08,1.321042e+08,1.375462e+08,4.053987e+08,4.394249e+08,4.905334e+08,4.531585e+08,4.546110e+08,140000.000000,109240.000000,120000.000000,123000.000000,123000.00000

In [6]:
df.isnull().sum()

Crop                     0
State                    0
Season                   0
Area-2020-21          1307
Area-2021-22           647
Area-2022-23          1236
Area-2023-24          1229
Area-2024-25          1221
Production-2020-21    1307
Production-2021-22     233
Production-2022-23    1236
Production-2023-24    1229
Production-2024-25    1221
Yield-2020-21         1307
Yield-2021-22          647
Yield-2022-23         1236
Yield-2023-24         1229
Yield-2024-25         1221
dtype: int64

## Data Normalization – Part 1
---
The dataset currently contains **year-wise columns** for each metric, for example:

* `Area-2020-21`, `Area-2021-22`, …
* `Production-2020-21`, `Production-2021-22`, …
* `Yield-2020-21`, `Yield-2021-22`, …

To make the data **analysis-ready**, we will normalize it by:

1. **Melting the year-wise columns** into a single `Year` column.
2. Creating separate columns for `Area`, `Production`, and `Yield`.
3. Aggregating the values by **Crop, State, and Year**, so that each row represents a **unique Crop–State–Season combination**.

This normalization enables:

* Easier **time-series analysis** across seasons,
* Simpler **visualizations**, and
* More consistent **aggregations and calculations** by crop, state, or season.

In [7]:
id_cols = ["Crop", "State", "Season"]

area_df = df.melt(
    id_vars=id_cols,
    value_vars=[c for c in df.columns if c.startswith("Area-")],
    var_name="Year",
    value_name="Area"
)
area_df["Year"] = area_df["Year"].str.replace("Area-", "")

prod_df = df.melt(
    id_vars=id_cols,
    value_vars=[c for c in df.columns if c.startswith("Production-")],
    var_name="Year",
    value_name="Production"
)
prod_df["Year"] = prod_df["Year"].str.replace("Production-", "")

yield_df = df.melt(
    id_vars=id_cols,
    value_vars=[c for c in df.columns if c.startswith("Yield-")],
    var_name="Year",
    value_name="Yield"
)
yield_df["Year"] = yield_df["Year"].str.replace("Yield-", "")

final_df = (
    area_df
    .merge(prod_df, on=id_cols + ["Year"], how="left")
    .merge(yield_df, on=id_cols + ["Year"], how="left")
)

final_df = final_df.dropna(subset=["Area", "Production", "Yield"], how="all")

In [8]:
final_df

,Crop,State,Season,Year,Area,Production,Yield
0,Rice,Andaman And Nicobar Islands,Kharif,2020-21,6256.0,13344.05,2133.0
2,Rice,Andaman And Nicobar Islands,Total,2020-21,6256.0,13344.05,2133.0
3,Rice,Andhra Pradesh,Kharif,2020-21,1496000.0,4211240.00,2815.0
4,Rice,Andhra Pradesh,Rabi,2020-21,827500.0,3671617.50,4437.0
5,Rice,Andhra Pradesh,Total,2020-21,2323500.0,7882857.50,3393.0
...,...,...,...,...,...,...,...
16943,Guarseed,Punjab,Total,2024-25,8500.0,6358.00,748.0
16944,Guarseed,Rajasthan,Kharif,2024-25,2982561.0,1974455.00,662.0
16945,Guarseed,Rajasthan,Total,2024-25,2982561.0,1974455.00,662.0
16948,Guarseed,All India,Kharif,2024-25,3221751.0,2203934.66,684.0
16949,Guarseed,All India,Total,2024-25,3221751.0,2203934.66,684.0

In [9]:
# (final_df["Season"] == "Total").sum()
len(final_df[final_df["Season"] == "Total"])

4741

## Removing Aggregated Seasonal Data
---
The dataset includes rows where the season is labeled **"Total"**, which represent aggregated values across seasons.

Since this analysis focuses on **actual seasonal production patterns**, these rows are removed to avoid:

- double counting
- biased analysis

Only **individual seasons (e.g., Kharif, Rabi)** are retained.

In [10]:
final_df = final_df[final_df["Season"] != "Total"].reset_index(drop=True)

In [11]:
final_df.shape

(6990, 7)

In [12]:
final_df

,Crop,State,Season,Year,Area,Production,Yield
0,Rice,Andaman And Nicobar Islands,Kharif,2020-21,6256.0,13344.05,2133.0
1,Rice,Andhra Pradesh,Kharif,2020-21,1496000.0,4211240.00,2815.0
2,Rice,Andhra Pradesh,Rabi,2020-21,827500.0,3671617.50,4437.0
3,Rice,Arunachal Pradesh,Kharif,2020-21,133270.0,246416.23,1849.0
4,Rice,Arunachal Pradesh,Rabi,2020-21,495.0,663.30,1340.0
...,...,...,...,...,...,...,...
6985,Guarseed,Gujarat,Kharif,2024-25,85230.0,62388.36,732.0
6986,Guarseed,Haryana,Kharif,2024-25,145460.0,160733.30,1105.0
6987,Guarseed,Punjab,Kharif,2024-25,8500.0,6358.00,748.0
6988,Guarseed,Rajasthan,Kharif,2024-25,2982561.0,1974455.00,662.0
6989,Guarseed,All India,Kharif,2024-25,3221751.0,2203934.66,684.0

## Data Normalization – Part 2
---
To improve consistency and readability:

1. Column names are converted to **lowercase**
2. Units are standardized for easier interpretation

Conversions performed:

- Area: from hectares (Ha) → million hectares (Mha)
- Production: from tonnes → million tonnes (Mt)

*`Note:`Yield is kept in its original unit (Kg/Ha), since it is a ratio of production to area and does not require scaling.*

These transformations make the dataset easier to analyze and compare across crops and states.

In [13]:
#  normalise the data
# lowercase the column names
final_df.columns = final_df.columns.str.lower()

In [14]:
final_df["area_mha"] = final_df["area"] / 1_000_000  # conveting to million hecters
final_df["production_mt"] = final_df["production"] / 1_000_000  # conveting to million tonnes

In [15]:
final_df.isnull().sum()

crop               0
state              0
season             0
year               0
area             265
production         4
yield            265
area_mha         265
production_mt      4
dtype: int64

## Adding Data Quality Flag
---
To improve data reliability, a **Data Quality Flag** is introduced to differentiate between:

* **Valid zero-production seasons** (genuinely no production),
* **Partial or incomplete reporting**, and
* **Structurally missing records**.

This enables tailored filtering depending on the analysis requirements.

The flags are categorized into three groups:

* **Zero Production:** All three — area, production, and yield — equal zero, indicating a valid zero-production season.
* **Good:** At least one of the area, production, or yield values is greater than zero, representing reliable data.
* **Insufficient:** Data points with missing (`NaN`) values or inconsistent entries that do not meet the above criteria.

In [16]:
cols = ["area_mha", "production_mt", "yield"]

def data_quality_flag(row):
    values = row[cols].infer_objects(copy=False)

    # Case 1: all explicitly zero → valid no-production season
    if values.fillna(0).eq(0).all() and values.notna().all():
        return "ZERO_PRODUCTION"

    # Case 2: at least one meaningful value
    if (values > 0).any():
        return "GOOD"

    # Case 3: everything else (zeros + NaNs)
    return "INSUFFICIENT"

final_df["data_quality_flag"] = final_df.apply(data_quality_flag, axis=1)

In [17]:
final_df["data_quality_flag"].value_counts()

data_quality_flag
GOOD               6199
ZERO_PRODUCTION     522
INSUFFICIENT        269
Name: count, dtype: int64

In [18]:
final_df.crop.unique()

array(['Rice', 'Wheat', 'Maize', 'Barley', 'Jowar', 'Bajra', 'Ragi',
       'Small Millets', 'Shree Anna /Nutri Cereals',
       'Nutri/Coarse Cereals', 'Cereals', 'Tur', 'Gram', 'Urad', 'Moong',
       'Lentil', 'Other Pulses', 'Total Pulses', 'Total Food Grains',
       'Groundnut', 'Castorseed', 'Sesamum', 'Nigerseed', 'Soybean',
       'Sunflower', 'Rapeseed & Mustard', 'Linseed', 'Safflower',
       'Total Oil Seeds', 'Sugarcane', 'Cotton', 'Jute', 'Mesta',
       'Jute & Mesta', 'Tobacco', 'Sannhemp', 'Guarseed'], dtype=object)

In [19]:
final_df.crop.value_counts()

crop
Total Food Grains            423
Cereals                      407
Total Pulses                 390
Total Oil Seeds              380
Nutri/Coarse Cereals         373
Rice                         327
Maize                        324
Other Pulses                 295
Urad                         284
Moong                        277
Groundnut                    267
Shree Anna /Nutri Cereals    256
Sunflower                    209
Sesamum                      207
Jowar                        205
Sugarcane                    162
Rapeseed & Mustard           158
Bajra                        156
Wheat                        152
Tur                          151
Gram                         144
Small Millets                131
Soybean                      123
Cotton                       121
Ragi                         121
Lentil                       114
Castorseed                   104
Linseed                      103
Barley                       101
Nigerseed                     86
Jute & Mesta                  82
Mesta                         81
Safflower                     79
Jute                          72
Tobacco                       66
Sannhemp                      36
Guarseed                      23
Name: count, dtype: int64

In [20]:
# Normalize crop naming
crop_map = {
    "Shree Anna /Nutri Cereals": "Nutri Cereals",
    "Nutri/Coarse Cereals": "Nutri Cereals",
}

# final_df.loc["Crop"] = final_df["Crop"].replace(crop_map)
final_df.loc[:, "crop"] = final_df["crop"].replace(crop_map)

## Validation of Aggregated Crops
---
The dataset includes an aggregated category **"Jute & Mesta"**, which should represent the sum of:

- Jute
- Mesta

To ensure data accuracy, a validation check compares:

Combined Production (Jute + Mesta)  
vs  
Reported Production (Jute & Mesta)

If the values match within a tolerance range, the record is considered consistent.

This validation helps detect **aggregation errors or inconsistencies in the dataset**.

In [21]:
def validate_jute_mesta(
    df: pd.DataFrame,
    abs_tol: float = 1.0,
    rel_tol: float = 0.01,
    drop_matches: bool = True
):
    """
    Validates 'Jute & Mesta' production against
    sum of 'Jute' and 'Mesta'.

    Parameters
    ----------
    drop_matches : bool
        If True, removes matching rows.
        If False, keeps all rows.

    Returns
    -------
    df_result : pd.DataFrame
    stats : dict
    """

    required_cols = {'state', 'year', 'season', 'crop', 'production_mt'}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    keys = ['state', 'year', 'season']
    df = df.copy()

    component_df = df[df['crop'].isin(['Jute', 'Mesta'])]

    expected_df = (
        component_df
        .groupby(keys, as_index=False)['production_mt']
        .sum()
        .rename(columns={'production_mt': 'expected_prod'})
    )

    combined_df = df[df['crop'] == 'Jute & Mesta']

    check_df = combined_df.merge(expected_df, on=keys, how='left')

    difference = (check_df['production_mt'] - check_df['expected_prod']).abs()

    pct_error = np.where(
        check_df['expected_prod'].notna() & (check_df['expected_prod'] != 0),
        difference / check_df['expected_prod'],
        np.nan
    )

    has_component = check_df['expected_prod'].notna()

    is_match = (
        has_component &
        ((difference <= abs_tol) | (pct_error <= rel_tol))
    )

    # Stats
    stats = {
        "total_jm_rows": len(check_df),
        "matches": int(is_match.sum()),
        "non_matches": int((~is_match & has_component).sum()),
        "no_component_data": int((~has_component).sum())
    }

    if drop_matches:
        df_result = pd.concat([
            df[df['crop'] != 'Jute & Mesta'],
            check_df.loc[~is_match, df.columns]
        ], ignore_index=True)
    else:
        df_result = df.copy()

    return df_result, stats

In [22]:
final_df, summary = validate_jute_mesta(final_df)
# final_df, summary = validate_jute_mesta(final_df, drop_matches=False)

In [23]:
print(summary)

{'total_jm_rows': 82, 'matches': 82, 'non_matches': 0, 'no_component_data': 0}

In [24]:
final_df.head()

,crop,state,season,year,area,production,yield,area_mha,production_mt,data_quality_flag
0,Rice,Andaman And Nicobar Islands,Kharif,2020-21,6256.0,13344.05,2133.0,0.006256,0.013344,GOOD
1,Rice,Andhra Pradesh,Kharif,2020-21,1496000.0,4211240.00,2815.0,1.496000,4.211240,GOOD
2,Rice,Andhra Pradesh,Rabi,2020-21,827500.0,3671617.50,4437.0,0.827500,3.671617,GOOD
3,Rice,Arunachal Pradesh,Kharif,2020-21,133270.0,246416.23,1849.0,0.133270,0.246416,GOOD
4,Rice,Arunachal Pradesh,Rabi,2020-21,495.0,663.30,1340.0,0.000495,0.000663,GOOD

In [25]:
final_df['is_total'] = final_df['crop'].str.lower().str.startswith('total')

In [26]:
final_df.is_total.value_counts()

is_total
False    5715
True     1193
Name: count, dtype: int64

In [27]:
final_df

,crop,state,season,year,area,production,yield,area_mha,production_mt,data_quality_flag,is_total
0,Rice,Andaman And Nicobar Islands,Kharif,2020-21,6256.0,13344.05,2133.0,0.006256,0.013344,GOOD,False
1,Rice,Andhra Pradesh,Kharif,2020-21,1496000.0,4211240.00,2815.0,1.496000,4.211240,GOOD,False
2,Rice,Andhra Pradesh,Rabi,2020-21,827500.0,3671617.50,4437.0,0.827500,3.671617,GOOD,False
3,Rice,Arunachal Pradesh,Kharif,2020-21,133270.0,246416.23,1849.0,0.133270,0.246416,GOOD,False
4,Rice,Arunachal Pradesh,Rabi,2020-21,495.0,663.30,1340.0,0.000495,0.000663,GOOD,False
...,...,...,...,...,...,...,...,...,...,...,...
6903,Guarseed,Gujarat,Kharif,2024-25,85230.0,62388.36,732.0,0.085230,0.062388,GOOD,False
6904,Guarseed,Haryana,Kharif,2024-25,145460.0,160733.30,1105.0,0.145460,0.160733,GOOD,False
6905,Guarseed,Punjab,Kharif,2024-25,8500.0,6358.00,748.0,0.008500,0.006358,GOOD,False
6906,Guarseed,Rajasthan,Kharif,2024-25,2982561.0,1974455.00,662.0,2.982561,1.974455,GOOD,False
6907,Guarseed,All India,Kharif,2024-25,3221751.0,2203934.66,684.0,3.221751,2.203935,GOOD,False

## Removing All India from State Column
---
Removing `All India` because it represents the total aggregated production for the entire country, which is not needed for our analysis.

In [28]:
# Remove "All India" rows
final_df.drop(
    final_df[final_df["state"] == "All India"].index,
    inplace=True
)

# Remove rows where is_total == True
final_df.drop(
    final_df[final_df["is_total"] == True].index,
    inplace=True
)

# Drop the column
final_df.drop(columns=["is_total"], errors="ignore", inplace=True)

In [29]:
final_df.state.unique()

array(['Andaman And Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra And Nagar Haveli', 'Daman And Diu', 'Delhi',
       'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu And Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal', 'Ladakh', 'Lakshadweep'],
      dtype=object)

In [30]:
final_df.crop.unique()

array(['Rice', 'Wheat', 'Maize', 'Barley', 'Jowar', 'Bajra', 'Ragi',
       'Small Millets', 'Nutri Cereals', 'Cereals', 'Tur', 'Gram', 'Urad',
       'Moong', 'Lentil', 'Other Pulses', 'Groundnut', 'Castorseed',
       'Sesamum', 'Nigerseed', 'Soybean', 'Sunflower',
       'Rapeseed & Mustard', 'Linseed', 'Safflower', 'Sugarcane',
       'Cotton', 'Jute', 'Mesta', 'Tobacco', 'Sannhemp', 'Guarseed'],
      dtype=object)

## Adding Crop Category
---
A Crop Category column is introduced to group crops into broader categories based on their type and usage.

This categorization allows Aggregated analysis by crop type, Easier comparison across categories, and Simplified visualization of production patterns.

In [31]:
category_map = {
    # Food Grains
    'food_grains' : [
        "Nutri Cereals", "Cereals", "Rice", "Maize", "Jowar", 
        "Bajra", "Wheat", "Small Millets", "Ragi", "Barley"
    ],
    # Pulses
    'pulses' : [
        "Other Pulses", "Urad", "Moong", "Tur", "Gram", "Lentil"
    ],
    # Oilseeds
    'oilseeds' : [
        "Groundnut", "Sunflower", "Sesamum", "Rapeseed & Mustard", 
        "Soybean", "Castorseed", "Linseed", "Nigerseed", "Safflower", "Guarseed"
    ],

    # Remaining / Other Crops
    "industrial_crops" : [
        "Cotton", "Sugarcane", "Tobacco", "Jute", "Mesta", "Sannhemp"
    ],
}

In [32]:
crop_to_category = {
    crop: category
    for category, crops in category_map.items()
    for crop in crops
}

final_df["crop_category"] = final_df["crop"].map(crop_to_category)

In [33]:
final_df.crop_category.value_counts()

crop_category
food_grains         2447
oilseeds            1288
pulses              1214
industrial_crops     510
Name: count, dtype: int64

In [34]:
final_df.shape

(5459, 11)

In [35]:
final_df.to_csv("../data/clean/agristats_clean.csv",index = False)